---
- name: Deploy P2P Services
  hosts: localhost
  tasks:
    - name: Stop docker-compose services
      shell: docker-compose down
      args:
        chdir: "{{ lookup('env', 'WORKSPACE') }}"

    - name: Start docker-compose services
      shell: docker-compose up -d
      args:
        chdir: "{{ lookup('env', 'WORKSPACE') }}"